# -*- coding: utf-8 -*-
"""Posttest 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KG7xT05pAbfUl1yFWooVvqVc9-5q_dKk
"""

# LOGIN ADMIN
username = "Ammar Nabil Fauzan"
password = "ammarnabil21"

print("""
        TOKO FURNITUR
      -----------------
Silahkan masuk dengan akun ADMIN
""")

while True:
    username1 = str(input("Username: "))
    password1 = str(input("Password: "))

    if username1 != username and password1 != password:
        print("Username atau Password anda tidak benar")
    else:
        break

furnitur = ["Kasur", "Kursi", "Meja", "Lemari", "Rak minimalis", "Kabinet dapur"]
harga = [5000000, 99000, 250000, 650000, 100000, 2500000]
keranjang = []
harga_dikeranjang = []
member_acc = {
    "ammar" : "nabil"
}

def register():
    bisa = False
    while not bisa:
        user = str(input("Username baru: "))
        pw = str(input("Password: "))

        if user not in member_acc:
            member_acc[user]=pw
            print("Akun sudah didaftarkan")
            print(f"""
                     ***Akun Member***
                    username: {user}
                    paswword: {pw}""")
            bisa = True

        else:
            print("Username sudah digunakan")


def login():
    bisa = False
    while not bisa:
        user = str(input("Username: "))
        pw = str(input("Password: "))

        if user in member_acc and member_acc[user] == pw:
            print("Selamat Datang, Wahai Memberku",user)
            bisa = True
        else:
            print("Akun tidak ditemukan")


while True:
    print("""
          TOKO FURNITUR
        -----------------
  1. Pendataan toko
  2. Pelayanan Pelanggan
  3. Keluar
    """)

    pilihan1 = input("Pilih opsi: ")

    if pilihan1 == "1":
        print("""
             TOKO FURNITUR
           -----------------
       1. Menambah data barang
       2. Menampilkan semua data barang
       3. Memperbarui data barang
       4. Menghapus data barang
       5. Mencari barang
       6. Kembali
       """)

        pilihan2 = input("Pilih opsi: ")

        if pilihan2 == "1":
            update1 = input("Masukkan barang yang ingin ditambah: ")
            update2 = input("Masukkan harga yang ingin ditambah: ")
            furnitur.append(update1)
            harga.append(int(update2))
        elif pilihan2 == "2":
            print("Furnitur".ljust(20) + "Harga")
            print("=" * 25)
            for i in range(len(furnitur)):
                print(furnitur[i].ljust(20) + str(harga[i]))
        elif pilihan2 == "3":
            update1 = input("Masukkan barang yang ingin diupdate: ")
            if update1 in furnitur:
                index_furnitur = furnitur.index(update1)
                harga[index_furnitur] = update2
            else:
                print("Barang tidak ditemukan")
        elif pilihan2 == "4":
            hapus_barang = input("Pilih barang yang ingin dihapus: ")
            if hapus_barang in furnitur:
                index_furnitur = furnitur.index(hapus_barang)
                del furnitur[index_furnitur]
                del harga[index_furnitur]
            else:
                print("Barang tidak ditemukan.")
        elif pilihan2 == "5":
            cari = str(input("Cari barang apa? : "))
            found = False
            for i in range(len(furnitur)):
                if cari.lower() in furnitur[i].lower():
                    print(furnitur[i].ljust(20) + str(harga[i]))
                    found = True
            if not found:
                print("Barang tidak ditemukan")
        elif pilihan2 == "6":
            continue
        else:
            print("Input tidak sesuai")
    elif pilihan1 == "2":
        print("""
          TOKO FURNITUR
        -----------------
  1. Akun member
  2. Non-member
  3. Kembali
    """)

        pilihan3 = input("Pilih opsi: ")

        if pilihan3 == "1":
            print("""
          TOKO FURNITUR
        -----------------
             (MEMBER)

  1. Login
  2. Register
  3. Kembali
    """)

            pilihan5 = input("Pilih opsi: ")

            if pilihan5 == "1": #LOGIN MEMBER
                print(" Silahkan Login Dengan Akun Member Anda")
                login()

                while True:
                    print("""
              TOKO FURNITUR
            -----------------
                 (MEMBER)

            1. Isi keranjang
            2. Cek keranjang
            3. Bayar
            4. Kembali
                """)

                    pilihan4 = input("Pilih opsi:")

                    if pilihan4 == "1":
                        while True:
                            for i in range(len(furnitur)):
                                print()
                                print(f"{i}. {furnitur[i]} = {harga[i]}")

                            pilih = input("\nPilih barang (Jika sudah cukup, ketik selesai): ")

                            if pilih.lower() == "selesai":
                                break
                            try:
                                index = int(pilih)
                                if 0 <= index < len(furnitur):
                                    barang_dipilih = furnitur[index]
                                    harga_dipilih = harga[index]
                                    keranjang.append(barang_dipilih)
                                    harga_dikeranjang.append(harga_dipilih)
                                    print(f"Barang {barang_dipilih} telah ditambahkan ke dalam keranjang anda")
                                else:
                                    print("Nomor index tidak valid")
                            except ValueError:
                                print("Masukkan nomor index yang valid")

                    elif pilihan4 == "2":
                        totalharga = sum(harga_dikeranjang)
                        print("Isi Keranjang:")
                        for i in range(len(keranjang)):
                            print(f">>> {keranjang[i]} harga({harga_dikeranjang[i]})")
                            print(f"Total harga >>> {totalharga}")

                    elif pilihan4 == "3":
                        uang = int(input("Tunai: "))
                        diskon = totalharga*10/100
                        totalharga2 = totalharga - diskon
                        kembali = uang - totalharga2

                        if uang >= totalharga:
                            print(" STRUK BELANJA")
                            for item, harga_item in zip(keranjang, harga_dikeranjang):
                                print(f">>> {item} harga({harga_item})")
                            print(f"Tunai : {uang}")
                            print(f"Total : {totalharga}")
                            print(f"Diskon: {diskon}")
                            print(f"Kembalian anda: {kembali}")
                            print("akun member")

                        else:
                            print("Uang anda tidak cukup")

                    elif pilihan4 == "4":
                        break

            elif pilihan5 == "2":
                print("##_REGISTRASI AKUN MEMBER_##")
                register()

            elif pilihan5 == "3":
                continue

        elif pilihan3 == "2":
            print("""
      TOKO FURNITUR
    -----------------
        (NON-MEMBER)

  1. Isi keranjang
  2. Cek keranjang
  3. Bayar
  4. Kembali
      """)

            pilihan4 = input("Pilih opsi:")

            if pilihan4 == "1":
                while True:
                    for i in range(len(furnitur)):
                        print()
                        print(f"{i}. {furnitur[i]} = {harga[i]}")
                    pilih = input("\nPilih barang (Jika sudah cukup, ketik selesai): ")

                    if pilih.lower() == "selesai":
                        break
                    try:
                        index = int(pilih)
                        if 0 <= index < len(furnitur):
                            barang_dipilih = furnitur[index]
                            harga_dipilih = harga[index]
                            keranjang.append(barang_dipilih)
                            harga_dikeranjang.append(harga_dipilih)
                            print(f"Barang {barang_dipilih} telah ditambahkan ke dalam keranjang anda")
                        else:
                            print("Nomor index tidak valid")
                    except ValueError:
                        print("Masukkan nomor index yang valid")

            elif pilihan4 == "2":
                totalharga = sum(harga_dikeranjang)
                print("Isi Keranjang:")
                for i in range(len(keranjang)):
                    print(f">>> {keranjang[i]} harga({harga_dikeranjang[i]})")
                print(f"Total harga >>> {totalharga}")

            elif pilihan4 == "3":
                uang = int(input("Tunai: "))
                kembali = uang - totalharga
                if uang >= totalharga:
                    print("STRUK BELANJA")
                    for item, harga_item in zip(keranjang, harga_dikeranjang):
                        print(f">>>{item} ({harga_item})")
                    print(f"Tunai        : {uang}")
                    print(f"Total        : {totalharga}")
                    print(f"Kembali      : {kembali}")
                    print("non-member")

                else:
                    print("Uang anda tidak cukup")

            elif pilihan4 == "4":
                continue

        elif pilihan3 == "3":
            continue

    elif pilihan1 == "3":
        print("Program selesai")
        break

    else:
        print("Input tidak sesuai")